### ISSUE TITLE
RISC-V compliance test

### ISSUE THREAD

**Issue by WeiCheng14159** [ria-jit/ria-jit#2]
Hi, 

I am curious whether this DBT is capable passing riscv-compliance test in this [repo](https://github.com/riscv/riscv-compliance) or whether you are interested in implementing this feature in the near future ? 

BTW your work is amazing, implementing a DBT that out performs qemu is exceptional. Thanks you all for making it open source.

**Comment by ndormann** [comment]
Hi,

thank you very much. Unfortunately, this project was part of a course assignment and thus, is not actively continued anymore. I think one needs to support the Priviliged Spec, which we do not (yet), for running the mentioned framework. RIA-JIT is only for user space emulation. 
However if you are interested in continuing this project, I am happy to help.
Best Noah

**Comment by WeiCheng14159** [comment]
Thanks for your reply ! 

Actually I have successfully run all rv64im compliance tests on RIA-JIT
RIA-JIT didn't pass one of the test and that's how I spot a divide by zero bug
I will open a pull request later

I think this is a very interesting project to work on !
If I have any question I will open another issue. Leave some comment if you have time (No pressure no hurry though)

Best Michael :D

**Comment by ndormann** [comment]
Great work! If you'd like you could also add the compliance test results to the documentation.
We are happy to respond to any further issues.

Best Noah
